# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Test Cases

on:
  push:
    tags:
      - 'v*'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Setup .NET SDK 9.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'
  
    - name: Restore dependencies
      run: dotnet restore

    - name: Clean project
      run: dotnet clean

    - name: Build project
      run: dotnet build --configuration Debug

    - name: Verify test output
      run: ls -R test/Aymadoka.Static.Extensions.Tests/bin/Debug/net9.0

    - name: Run tests
      run: dotnet test test/Aymadoka.Static.Extensions.Tests/Aymadoka.Static.Extensions.Tests.csproj --logger "trx;LogFileName=test_results.trx" --verbosity diagnostic

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: Test Results
        path: test/Aymadoka.Static.Extensions.Tests/TestResults/