# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Publish NuGet Package

on:
  push:
    tags:
      - 'v*'  # 仅当提交带有类似 v1.0.0 的 tag 时触发发布流程

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK 9.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # - name: Run tests
    #   run: dotnet test test/Aymadoka.Static.Extensions.Tests/Aymadoka.Static.Extensions.Tests.csproj --no-build --verbosity detailed

    - name: Pack NuGet package
      run: dotnet pack src/Aymadoka.Static.Extensions/Aymadoka.Static.Extensions.csproj --configuration Release -o ./nupkgs

    - name: Publish to NuGet.org
      if: success()
      env:
        NUGET_API_KEY: ${{ secrets.AYMADOKA_STATIC_EXTENSIONS_NUGET_API_KEY }}
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json